### ISSUE TITLE
Slot hierarchy isn't generated locally   

### ISSUE THREAD

**Issue by Crusher50** [art0007i/MyInspectors#2]
Currently the slot hierarchy is still generated by the host. This may not effect most as the hierarchy isn't affected by any mods that this mod was originally intended for. 

The reason I ask for this feature request is that it would allow people that are desynced to still be able to use the inspector without having to wait for the host to generate the rest of the UI. (the half that is currently local works perfectly with this mod and generates immediately even when desynced.) 

However, if this is out of the scope for this project you can close this issue.

**Comment by art0007i** [comment]
solved in [1.3.0](https://github.com/art0007i/MyInspectors/releases/tag/1.3.0)
